; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino

; USB Stack auf TinyUSB setzen
build_flags = 
    -DUSE_TINYUSB
    -DADAFRUIT_TINYUSB_ENABLED

; Libraries
lib_deps = 
    adafruit/Adafruit TinyUSB Library @ ^3.7.7
    fortyseveneffects/MIDI Library @ ^5.0.2
    adafruit/Adafruit SSD1306 @ ^2.5.17
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit BusIO @ ^1.16.3

; Upload & Monitor
upload_protocol = picotool
monitor_speed = 115200